//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokefeet2.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pokefeet2.Ressources.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        public static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is created by.
        /// </summary>
        public static string Createdby {
            get {
                return ResourceManager.GetString("Createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat!.
        /// </summary>
        public static string Defeat {
            get {
                return ResourceManager.GetString("Defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string dialog_credit {
            get {
                return ResourceManager.GetString("dialog_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gotta Guess &apos;Em All!.
        /// </summary>
        public static string dialog_guessthemall {
            get {
                return ResourceManager.GetString("dialog_guessthemall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge yourself and see if you can identify all the Pokémon by their footprints. Good luck, Pokémon Trainer!.
        /// </summary>
        public static string dialog_guessthemall_desc {
            get {
                return ResourceManager.GetString("dialog_guessthemall_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play.
        /// </summary>
        public static string dialog_howtoplay {
            get {
                return ResourceManager.GetString("dialog_howtoplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Guess the Pokémon:&lt;/b&gt; Initially, you will be shown a Pokémon footprint with no additional clues. Take your best guess at the Pokémon&apos;s name. For example, if you see a footprint that looks like it could be Pikachu&apos;s, type &quot;Pikachu&quot; and hit enter.
        ///
        ///&lt;br /&gt;
        ///
        ///&lt;b&gt;Correct Guess:&lt;/b&gt; If your guess is correct, congratulations! You&apos;ve identified the Pokémon. Wait the next day to guess another one !
        ///
        ///&lt;br /&gt;
        ///
        ///&lt;b&gt;Wrong Guess:&lt;/b&gt; If you guess incorrectly, don&apos;t worry. You have a limited number of tries. Afte [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dialog_howtoplay_desc {
            get {
                return ResourceManager.GetString("dialog_howtoplay_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the world of POKEMON!
        ///&lt;br/&gt;&lt;br/&gt;
        ///In this game, you will be presented with mysterious Pokémon footprints, and it&apos;s your task to identify the Pokémon associated with each footprint. 
        ///Put your Pokémon knowledge to the test and see how many you can guess correctly!
        ///.
        /// </summary>
        public static string dialog_Welcome {
            get {
                return ResourceManager.GetString("dialog_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation.
        /// </summary>
        public static string Generation {
            get {
                return ResourceManager.GetString("Generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is heavily inspired by the following sites:.
        /// </summary>
        public static string HeavilyInspiredBy {
            get {
                return ResourceManager.GetString("HeavilyInspiredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary.
        /// </summary>
        public static string Legendary {
            get {
                return ResourceManager.GetString("Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mythical.
        /// </summary>
        public static string Mythical {
            get {
                return ResourceManager.GetString("Mythical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next Pokémon will appear in:.
        /// </summary>
        public static string NextPokemonIn {
            get {
                return ResourceManager.GetString("NextPokemonIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t guessed:.
        /// </summary>
        public static string NoGuessed {
            get {
                return ResourceManager.GetString("NoGuessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokeball Loading.
        /// </summary>
        public static string Pkball_Loading {
            get {
                return ResourceManager.GetString("Pkball_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code:.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to:.
        /// </summary>
        public static string ThanksTo {
            get {
                return ResourceManager.GetString("ThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory!.
        /// </summary>
        public static string Victory {
            get {
                return ResourceManager.GetString("Victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who&apos;s that pokemon?.
        /// </summary>
        public static string WhosThatPokemon {
            get {
                return ResourceManager.GetString("WhosThatPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You guessed:.
        /// </summary>
        public static string YouGuessed {
            get {
                return ResourceManager.GetString("YouGuessed", resourceCulture);
            }
        }
    }
}
